In [50]:
import pandas as pd
import numpy as np

pd.set_option('display.float_format', lambda x: '%.2f' % x)

sales = pd.read_csv(r"C:\Users\Kevin\Desktop\project_transactions.csv")

In [51]:
sales.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
0,1364,26984896261,1,842930,1,2.19,31742,0.00,1,0.00,0.00
1,1364,26984896261,1,897044,1,2.99,31742,-0.40,1,0.00,0.00
2,1364,26984896261,1,920955,1,3.09,31742,0.00,1,0.00,0.00
3,1364,26984896261,1,937406,1,2.50,31742,-0.99,1,0.00,0.00
4,1364,26984896261,1,981760,1,0.60,31742,-0.79,1,0.00,0.00

In [52]:
sales.describe().round(2)

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,RETAIL_DISC,WEEK_NO,COUPON_DISC,COUPON_MATCH_DISC
count,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00,2146311.00
mean,1056.23,34048967698.37,389.51,2884714.94,100.97,3.11,3267.94,-0.53,56.33,-0.02,-0.00
std,605.01,4723747571.85,190.05,3831949.29,1152.36,4.19,9122.39,1.23,27.15,0.21,0.04
min,1.00,26984896261.00,1.00,25671.00,0.00,0.00,1.00,-130.02,1.00,-55.93,-7.70
25%,548.00,30407979445.00,229.00,917231.00,1.00,1.29,330.00,-0.68,33.00,0.00,0.00
50%,1042.00,32811761450.00,392.00,1027960.00,1.00,2.00,372.00,0.00,57.00,0.00,0.00
75%,1581.00,40128035453.00,555.00,1132771.00,1.00,3.49,422.00,0.00,80.00,0.00,0.00
max,2099.00,42305362535.00,711.00,18316298.00,89638.00,840.00,34280.00,3.99,102.00,0.00,0.00

In [53]:
sales.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 2146311 entries, 0 to 2146310
Data columns (total 11 columns):
 #   Column             Dtype
---  ------             -----
 0   household_key      int64
 1   BASKET_ID          int64
 2   DAY                int64
 3   PRODUCT_ID         int64
 4   QUANTITY           int64
 5   SALES_VALUE        float64
 6   STORE_ID           int64
 7   RETAIL_DISC        float64
 8   WEEK_NO            int64
 9   COUPON_DISC        float64
 10  COUPON_MATCH_DISC  float64
dtypes: float64(4), int64(7)
memory usage: 180.1 MB

In [54]:
sales["DAY"] = sales["DAY"].astype("int8")
sales["QUANTITY"] = sales["QUANTITY"].astype("int32")
sales["STORE_ID"] = sales["STORE_ID"].astype("int32")
sales["WEEK_NO"] = sales["WEEK_NO"].astype("uint8")

In [55]:
sales.isna().sum()

household_key        0
BASKET_ID            0
DAY                  0
PRODUCT_ID           0
QUANTITY             0
SALES_VALUE          0
STORE_ID             0
RETAIL_DISC          0
WEEK_NO              0
COUPON_DISC          0
COUPON_MATCH_DISC    0
dtype: int64

In [56]:
sales[["household_key", "PRODUCT_ID"]].nunique()

household_key     2099
PRODUCT_ID       84138
dtype: int64

In [57]:
sales["TOTAL_DISCOUNT"] = sales["RETAIL_DISC"] + sales["COUPON_DISC"]
sales["DISCOUNT_PERCENT"] = (sales["TOTAL_DISCOUNT"] / sales["SALES_VALUE"]).abs()
sales["DISCOUNT_PERCENT"] = sales["DISCOUNT_PERCENT"].clip(0, 1)
sales[["RETAIL_DISC", "COUPON_DISC", "TOTAL_DISCOUNT", "SALES_VALUE", "DISCOUNT_PERCENT"]].head()

   RETAIL_DISC  COUPON_DISC  TOTAL_DISCOUNT  SALES_VALUE  DISCOUNT_PERCENT
0         0.00         0.00            0.00         2.19              0.00
1        -0.40         0.00           -0.40         2.99              0.13
2         0.00         0.00            0.00         3.09              0.00
3        -0.99         0.00           -0.99         2.50              0.40
4        -0.79         0.00           -0.79         0.60              1.00

In [58]:
sales = sales.drop(["RETAIL_DISC", "COUPON_DISC", "COUPON_MATCH_DISC"], axis=1)

In [59]:
sales.head()

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,WEEK_NO,TOTAL_DISCOUNT,DISCOUNT_PERCENT
0,1364,26984896261,1,842930,1,2.19,31742,1,0.00,0.00
1,1364,26984896261,1,897044,1,2.99,31742,1,-0.40,0.13
2,1364,26984896261,1,920955,1,3.09,31742,1,0.00,0.00
3,1364,26984896261,1,937406,1,2.50,31742,1,-0.99,0.40
4,1364,26984896261,1,981760,1,0.60,31742,1,-0.79,1.00

In [61]:
sales[["SALES_VALUE", "TOTAL_DISCOUNT", "QUANTITY"]].sum()

SALES_VALUE        6666243.50
TOTAL_DISCOUNT    -1178658.08
QUANTITY         216713611.00
dtype: float64

In [67]:
overall_pct = (sales["TOTAL_DISCOUNT"].sum() / sales["SALES_VALUE"].sum())
overall_pct = abs(overall_pct)
overall_pct.round(2)

np.float64(0.18)

In [71]:
max_qty = sales["QUANTITY"].max()

max_qty_row = sales.loc[sales["QUANTITY"] == max_qty]

print(f"Suurim kogus: {max_qty}")
max_qty_row

Suurim kogus: 89638

,household_key,BASKET_ID,DAY,PRODUCT_ID,QUANTITY,SALES_VALUE,STORE_ID,WEEK_NO,TOTAL_DISCOUNT,DISCOUNT_PERCENT
1442095,630,34749153595,-9,6534178,89638,250.00,384,73,-13.45,0.05