In [13]:
import pandas as pd

In [14]:
transactions = pd.read_csv(r"C:\Users\Kevin\Desktop\transactions.csv", parse_dates=["date"])

In [15]:
transactions.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [16]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [17]:
max_date = transactions["date"].max()

transactions = transactions.assign(
    year = transactions['date'].dt.year,
    month = transactions['date'].dt.month,
    dayofweek = transactions['date'].dt.dayofweek,
    days_since_max = max_date - transactions["date"]
)

In [18]:
transactions.head()

        date  store_nbr  transactions  year  month  dayofweek days_since_max
0 2013-01-01         25           770  2013      1          1      1687 days
1 2013-01-02          1          2111  2013      1          2      1686 days
2 2013-01-02          2          2358  2013      1          2      1686 days
3 2013-01-02          3          3487  2013      1          2      1686 days
4 2013-01-02          4          1922  2013      1          2      1686 days

In [19]:
transactions['date'] = transactions['date'].dt.strftime('%Y-%B-%d')
transactions.head(10)

,date,store_nbr,transactions,year,month,dayofweek,days_since_max
0,2013-January-01,25,770,2013,1,1,1687 days
1,2013-January-02,1,2111,2013,1,2,1686 days
2,2013-January-02,2,2358,2013,1,2,1686 days
3,2013-January-02,3,3487,2013,1,2,1686 days
4,2013-January-02,4,1922,2013,1,2,1686 days
5,2013-January-02,5,1903,2013,1,2,1686 days
6,2013-January-02,6,2143,2013,1,2,1686 days
7,2013-January-02,7,1874,2013,1,2,1686 days
8,2013-January-02,8,3250,2013,1,2,1686 days
9,2013-January-02,9,2940,2013,1,2,1686 days