In [9]:
import pandas as pd

In [10]:
retail = pd.read_csv(r"C:\Users\Kevin\Desktop\retail.csv", parse_dates=["date"])

In [11]:
retail.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054944 entries, 0 to 1054943
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   id           1054944 non-null  int64
 1   date         1054944 non-null  datetime64[ns]
 2   store_nbr    1054944 non-null  int64
 3   family       1054944 non-null  object
 4   sales        1054944 non-null  float64
 5   onpromotion  1054944 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 100.4 MB

In [15]:
retail = retail.assign(birthday=pd.to_datetime("1980-02-02"))
retail.head()

        id       date  store_nbr      family  sales  onpromotion   birthday
0  1945944 2016-01-01          1  AUTOMOTIVE    0.0            0 1980-02-02
1  1945945 2016-01-01          1   BABY CARE    0.0            0 1980-02-02
2  1945946 2016-01-01          1      BEAUTY    0.0            0 1980-02-02
3  1945947 2016-01-01          1   BEVERAGES    0.0            0 1980-02-02
4  1945948 2016-01-01          1       BOOKS    0.0            0 1980-02-02

In [19]:
retail = retail.assign(age= (retail["date"] - retail["birthday"]).dt.days / 365)
retail.head()

,id,date,store_nbr,family,sales,onpromotion,birthday,age
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,1980-02-02,35.936986
1,1945945,2016-01-01,1,BABY CARE,0.0,0,1980-02-02,35.936986
2,1945946,2016-01-01,1,BEAUTY,0.0,0,1980-02-02,35.936986
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,1980-02-02,35.936986
4,1945948,2016-01-01,1,BOOKS,0.0,0,1980-02-02,35.936986

In [22]:
retail = retail.assign(retirement_date = retail["date"] + (pd.to_timedelta(366, unit="D")))
retail.head()

,id,date,store_nbr,family,sales,onpromotion,birthday,age,retirement_date
0,1945944,2016-01-01,1,AUTOMOTIVE,0.0,0,1980-02-02,35.936986,2017-01-01
1,1945945,2016-01-01,1,BABY CARE,0.0,0,1980-02-02,35.936986,2017-01-01
2,1945946,2016-01-01,1,BEAUTY,0.0,0,1980-02-02,35.936986,2017-01-01
3,1945947,2016-01-01,1,BEVERAGES,0.0,0,1980-02-02,35.936986,2017-01-01
4,1945948,2016-01-01,1,BOOKS,0.0,0,1980-02-02,35.936986,2017-01-01