In [19]:
import pandas as pd

In [20]:
transactions = pd.read_csv(r"C:\Users\Kevin\Desktop\transactions.csv", parse_dates=["date"])

In [21]:
transactions.tail()

            date  store_nbr  transactions
83483 2017-08-15         50          2804
83484 2017-08-15         51          1573
83485 2017-08-15         52          2255
83486 2017-08-15         53           932
83487 2017-08-15         54           802

In [22]:
max_date = transactions["date"].max()

transactions = transactions.assign(
    year = transactions['date'].dt.year,
    month = transactions['date'].dt.month,
    dayofweek = transactions['date'].dt.dayofweek,
    days_since_max = max_date - transactions["date"]
)

In [23]:
transactions = transactions.assign(time_to_last_date = transactions["days_since_max"] + (pd.to_timedelta(21, unit="D"))).drop(columns=["days_since_max"])
transactions.head()

,date,store_nbr,transactions,year,month,dayofweek,time_to_last_date
0,2013-01-01,25,770,2013,1,1,1708 days
1,2013-01-02,1,2111,2013,1,2,1707 days
2,2013-01-02,2,2358,2013,1,2,1707 days
3,2013-01-02,3,3487,2013,1,2,1707 days
4,2013-01-02,4,1922,2013,1,2,1707 days

In [26]:
transactions = transactions.assign(weeks_to_last_date = transactions["time_to_last_date"] / (pd.to_timedelta(7, unit="D")))
transactions.head()

,date,store_nbr,transactions,year,month,dayofweek,time_to_last_date,weeks_to_last_date
0,2013-01-01,25,770,2013,1,1,1708 days,244.000000
1,2013-01-02,1,2111,2013,1,2,1707 days,243.857143
2,2013-01-02,2,2358,2013,1,2,1707 days,243.857143
3,2013-01-02,3,3487,2013,1,2,1707 days,243.857143
4,2013-01-02,4,1922,2013,1,2,1707 days,243.857143